# This is a basic workflow to help you get started with Actions

name: Verilog Build and Analysis

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 3
    container:
      image: ghcr.io/hdl/iverilog:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & run tests
        run: |
          iverilog -o design.o -c script/iverilog.include
          vvp design.o
          echo "Script has finished running."
